### ISSUE TITLE
An advice about not to use .ml domain

### ISSUE THREAD

**Issue by SukkaW** [dortania/dortania.github.io#3]
Although `.ml` domain is free and could be free forever (only if your website is small), but it is known to all that *The free thing is the most expensive*. I once own a `.ga` domain, which is operated by Freenom, Inc. (the company that run `.ml` as well). The company took my domain back just because my site became large and they requested me to pay for continuing using that *free* domain.

I strongly recommend to use a purchased domain (.com or .org) at the beginning, or just stick with `github.io` (which GitHub, Inc. won't take it back)

**Comment by khronokernel** [comment]
Thank you for the heads up, we quite appreciate it. We've decided to change back to the old GitHub.io sites but we'll still keep the .ml sites and just redirect them. Eventually we'll close them but people have been using it and would like to prevent breaking a bunch of links at once

PRs waiting for merge:
https://github.com/dortania/dortania.ml/pull/4
https://github.com/dortania/Wireless-Buyers-Guide/pull/2
https://github.com/dortania/vanilla-laptop-guide/pull/4
https://github.com/dortania/OpenCore-Desktop-Guide/pull/2
https://github.com/dortania/GPU-Buyers-Guide/pull/1
https://github.com/dortania/Getting-Started-With-ACPI/pull/2
https://github.com/dortania/Anti-Hackintosh-Buyers-Guide/pull/1

**Comment by khronokernel** [comment]
Fixed: https://github.com/dortania/dortania.github.io/commit/dd1461a352775ce036aa316b68b216c6bd774845
